export const PROPERTY_CATEGORIES = [
  { value: 'apartamento', label: 'Apartamento' },
  { value: 'casa', label: 'Casa' },
  { value: 'comercial', label: 'Comercial' },
  { value: 'condominio', label: 'Condomínio Fechado' },
  { value: 'duplex', label: 'Duplex' },
  { value: 'jk', label: 'JK' },
  { value: 'sobrado', label: 'Sobrado' },
  { value: 'studio', label: 'Studio' },
  { value: 'terreno', label: 'Terreno' },
  { value: 'vivenda', label: 'Vivenda' },
];

export const PROPERTY_LOCATIONS = [
  'Capão Novo',
  'Posto 4',
  'Posto 5',
  'Village',
];

export const AMENITIES_LIST = [
  // Área Privativa
  { id: 'furnished', label: 'Mobiliado', category: 'Privativa' },
  { id: 'air_conditioning', label: 'Ar Condicionado', category: 'Privativa' },
  { id: 'barbecue', label: 'Churrasqueira', category: 'Privativa' },
  { id: 'balcony', label: 'Sacada', category: 'Privativa' },
  { id: 'kitchen_cabinets', label: 'Cozinha Montada', category: 'Privativa' },
  { id: 'closet', label: 'Closet', category: 'Privativa' },
  { id: 'view_sea', label: 'Vista para o Mar', category: 'Privativa' },
  { id: 'view_panoramic', label: 'Vista Panorâmica', category: 'Privativa' },
  { id: 'heating', label: 'Calefação', category: 'Privativa' },
  { id: 'decorated', label: 'Decorado', category: 'Privativa' },
  { id: 'ofuro', label: 'Ofurô', category: 'Privativa' },

  // Segurança
  { id: 'security_24h', label: 'Portaria 24h', category: 'Segurança' },
  { id: 'alarm', label: 'Alarme', category: 'Segurança' },
  { id: 'cctv', label: 'Circuito TV', category: 'Segurança' },
  { id: 'electric_fence', label: 'Cerca Elétrica', category: 'Segurança' },
  { id: 'gate_house', label: 'Guarita', category: 'Segurança' },
  { id: 'intercom', label: 'Interfone', category: 'Segurança' },
  { id: 'wall', label: 'Muro', category: 'Segurança' },
  { id: 'railing', label: 'Gradil', category: 'Segurança' },
  { id: 'electric_gate', label: 'Portão Eletrônico', category: 'Segurança' },
  { id: 'disabled_access', label: 'Acesso Deficiente Físico', category: 'Segurança' },

  // Lazer
  { id: 'pool', label: 'Piscina', category: 'Lazer' },
  { id: 'heated_pool', label: 'Piscina Aquecida', category: 'Lazer' },
  { id: 'covered_pool', label: 'Piscina Coberta', category: 'Lazer' },
  { id: 'kids_pool', label: 'Piscina Infantil', category: 'Lazer' },
  { id: 'lap_pool', label: 'Piscina com Raia', category: 'Lazer' },
  { id: 'gym', label: 'Academia', category: 'Lazer' },
  { id: 'fitness_center', label: 'Fitness Center', category: 'Lazer' },
  { id: 'pilates_room', label: 'Sala de Pilates', category: 'Lazer' },
  { id: 'sauna', label: 'Sauna', category: 'Lazer' },
  { id: 'spa', label: 'Spa', category: 'Lazer' },
  { id: 'party_hall', label: 'Salão de Festas', category: 'Lazer' },
  { id: 'game_room', label: 'Sala de Jogos', category: 'Lazer' },
  { id: 'cinema_room', label: 'Sala de Cinema', category: 'Lazer' },
  { id: 'lan_house', label: 'Lan House', category: 'Lazer' },
  { id: 'garage_band', label: 'Garage Band', category: 'Lazer' },
  { id: 'playground', label: 'Playground', category: 'Lazer' },
  { id: 'kids_space', label: 'Espaço Kids', category: 'Lazer' },
  { id: 'teens_space', label: 'Espaço Teen', category: 'Lazer' },
  { id: 'toy_library', label: 'Brinquedoteca', category: 'Lazer' },
  { id: 'zen_space', label: 'Espaço Zen', category: 'Lazer' },
  { id: 'gourmet_space', label: 'Espaço Gourmet', category: 'Lazer' },
  { id: 'pergolas', label: 'Pergolados', category: 'Lazer' },
  { id: 'wooden_deck', label: 'Deck de Madeira', category: 'Lazer' },
  { id: 'wet_deck', label: 'Deck Molhado', category: 'Lazer' },
  { id: 'sports_court', label: 'Quadra Poliesportiva', category: 'Lazer' },
  { id: 'soccer_field', label: 'Campo de Futebol', category: 'Lazer' },
  { id: 'mini_soccer', label: 'Mini Cancha de Futebol', category: 'Lazer' },
  { id: 'walking_trail', label: 'Pista de Caminhada', category: 'Lazer' },
  { id: 'skate_track', label: 'Pista de Skate', category: 'Lazer' },
  { id: 'helipad', label: 'Helioponto', category: 'Lazer' },
  { id: 'marina', label: 'Marina', category: 'Lazer' },
  { id: 'lake', label: 'Lago(s)', category: 'Lazer' },
  { id: 'lounge', label: 'Lounge', category: 'Lazer' },
  { id: 'coworking', label: 'Coworking', category: 'Lazer' },
  { id: 'shared_laundry', label: 'Lavanderia Coletiva', category: 'Lazer' },

  // Estrutura Condominial / Predial
  { id: 'elevator', label: 'Elevador', category: 'Estrutura' },
  { id: 'panoramic_elevator', label: 'Elevador Panorâmico', category: 'Estrutura' },
  { id: 'building_automation', label: 'Automação Predial', category: 'Estrutura' },
  { id: 'internet_access', label: 'Acesso à Internet', category: 'Estrutura' },
  { id: 'solar_heater', label: 'Aquecedor Solar', category: 'Estrutura' },
  { id: 'gas_heating', label: 'Aquecimento a Gás', category: 'Estrutura' },
  { id: 'central_heating', label: 'Aquecimento Central', category: 'Estrutura' },
  { id: 'central_air', label: 'Ar Central', category: 'Estrutura' },
  { id: 'central_gas', label: 'Gás Central', category: 'Estrutura' },
  { id: 'individual_gas_meter', label: 'Medidor de Gás Individual', category: 'Estrutura' },
  { id: 'individual_water_meter', label: 'Hidrômetro Individual', category: 'Estrutura' },
  { id: 'emergency_generator', label: 'Gerador de Emergência', category: 'Estrutura' },
  { id: 'condo_storage', label: 'Depósito Condominial', category: 'Estrutura' },
  { id: 'individual_storage', label: 'Depósito Individual', category: 'Estrutura' },
  { id: 'visitor_parking', label: 'Estacionamento para Visitantes', category: 'Estrutura' },
  { id: 'rotating_parking', label: 'Estacionamento Rotativo', category: 'Estrutura' },
  { id: 'bike_rack', label: 'Bicicletário', category: 'Estrutura' },
  { id: 'hall', label: 'Hall', category: 'Estrutura' },
  { id: 'garden', label: 'Jardim', category: 'Estrutura' },
  { id: 'green_area', label: 'Área Verde', category: 'Estrutura' },
  { id: 'living_area', label: 'Área de Convivência', category: 'Estrutura' },
  { id: 'shopping_center', label: 'Centro Comercial', category: 'Estrutura' },
  { id: 'cafeteria', label: 'Cafeteria', category: 'Estrutura' },
  { id: 'warehouse', label: 'Galpão', category: 'Estrutura' },
  { id: 'kennel', label: 'Canil', category: 'Estrutura' },
  { id: 'pet_care', label: 'Pet Care', category: 'Estrutura' },
  { id: 'pet_walk', label: 'Passeio Pet', category: 'Estrutura' },
  { id: 'beach_access', label: 'Entrada p/ Banhistas e Box de Praia', category: 'Estrutura' },
];

export const BUILDING_POSITIONS = [
  'Frente',
  'Fundos',
  'Lateral Direita',
  'Lateral Esquerda',
];

export const CARDINAL_DIRECTIONS = [
  'Norte',
  'Sul',
  'Leste',
  'Oeste',
  'Nordeste',
  'Sudeste',
  'Noroeste',
  'Sudoeste',
];

export const PROPERTY_STREETS = [
  'Avenida Paraguassu',
  'Avenida Almirante Tamandaré',
  'Avenida Osório',
  'Avenida das Dálias',
  'Avenida das Garças',
  'Avenida das Gardênias',
  'Avenida das Gaivotas',
  'Rua Bento Gonçalves',
  'Rua Caxias do Sul',
  'Rua das Margaridas',
  'Rua das Hortênsias',
  'Rua das Orquídeas',
  'Rua das Rosas',
  'Rua das Tulipas',
  'Rua das Violetas',
  'Rua do Amor-Perfeito',
  'Rua do Girassol',
  'Rua do Jasmim',
  'Rua do Lírio',
  'Rua das Magnólias',
  'Rua das Acácias',
  'Rua das Azaleias',
  'Rua dos Cravos',
  'Rua das Camélias',
  'Rua das Begônias',
].sort();

